config/routes.rb
Abdncc::Application.routes.draw do

  root :to => 'subjects#index'

  resources :courses
  resources :subjects
  resources :users do
    member do
      post 'add_course'
      post 'remove_course'
    end
  end
  resources :sessions, :except => [:edit, :show, :update, :index]
  resources :comments, :only => [:create, :destroy]

  match '/search' => 'courses#index', :as => :course_search, :via => :post

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  attr_accessible :content, :course_id, :user_id
  belongs_to :course
  belongs_to :user

  # validates_presence_of :course_id, :on => :create
  # validates_presence_of :user_id, :on => :create
  # validates_presence_of :content, :on => :create

# GRR DOESNT WORK WITH FACTORY DEFINITIONS!

end

# == Schema Information
#
# Table name: comments
#
#  id         :integer         not null, primary key
#  user_id    :integer
#  course_id  :integer
#  content    :text
#  created_at :datetime        not null
#  updated_at :datetime        not null
#

app/models/course.rb
class Course < ActiveRecord::Base
  attr_accessible :assessment, :ccode, :coordinator, :credits, :department, :description, :level, :name, :note, :prereq, :subject
  belongs_to :subject, :inverse_of => :courses
  has_and_belongs_to_many :users
  has_many :comments

  def rand_ccode
	  ccode = ''
	  2.times { ccode << ('A'..'Z').to_a[rand(0..25)].to_s }
	  ccode << ' '
	  4.times { ccode << rand(1..9).to_s }
	  ccode
  end
  
end

# == Schema Information
#
# Table name: courses
#
#  id          :integer         not null, primary key
#  name        :string(255)
#  ccode       :string(255)
#  credits     :integer
#  coordinator :string(255)
#  prereq      :string(255)
#  note        :text
#  description :text
#  assessment  :text
#  level       :integer
#  department  :string(255)
#  created_at  :datetime        not null
#  updated_at  :datetime        not null
#  subject_id  :integer
#  user_id     :integer
#

app/models/subject.rb
class Subject < ActiveRecord::Base
  attr_accessible :code, :courses, :name
  has_many :courses, :inverse_of => :subject

  def to_s
    self.name
  end

  def courses_where(options)
    self.courses.select { |course| course.level == options[:level] }
  end



end

# == Schema Information
#
# Table name: subjects
#
#  id         :integer         not null, primary key
#  name       :string(255)
#  code       :string(255)
#  course_id  :integer
#  created_at :datetime        not null
#  updated_at :datetime        not null
#

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  has_and_belongs_to_many :courses
  has_many :bookmarks, :class_name => 'Course'
  has_many :comments
  
  attr_accessible :email, :name, :status, :password, :status, :courses, :bookmarks

  validates_presence_of :password, :on => :create
  validates_presence_of :email, :on => :create
  validates :password, :length => { :in => 6..20 }
  validates_format_of :email, :with => /^[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}$/i
  validates_uniqueness_of :email

  attr_defaults :name => "Anonymous"

  def has_course?( course )
    self.courses.exists?( course ) ? true : false
  end

  def add_course( course )
    # if course.is_a? Course
      self.courses << course
    # elsif course.is_a? Fixnum
      # self.courses << Course.find( course )
    # end
  end

  def remove_course ( course )
    self.courses.delete course
  end
end

# == Schema Information
#
# Table name: users
#
#  id              :integer         not null, primary key
#  name            :string(255)
#  email           :string(255)
#  password_digest :string(255)
#  course_id       :integer
#  bookmark_id     :integer
#  created_at      :datetime        not null
#  updated_at      :datetime        not null
#  status          :string(255)
#

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  # force_ssl

  helper_method :current_user

  def current_user
    begin
      @current_user ||= User.find(session[:user_id]) if session[:user_id]
    rescue ActiveRecord::RecordNotFound
      nil
    end
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @comment = Comment.new(params[:comment])
    if @comment.save
      # handle successful creation of the comment
      redirect_to course_path(params[:comment][:course_id]), :notice => "Comment added!"
    else
      redirect_to course_path params[:comment][:course_id]
      # handle non-success
    end
  end
  
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController

  def show
    @course = Course.find params[:id]
    @comment = Comment.new
    unless current_user
      flash[:notice] = "Create an account or log in to start tracking this course"
    end
  end

  def index
    if params[:query]
      @courses = Course.search params[:query]
    else
      @courses = Course.all
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by_email params[:email]
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to user_path(user.id), :notice => "Logged in!"
    else
      flash.now.alert = "Invalid email or password"
      render "new"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, :notice => "Logged out!"
  end
end

app/controllers/subjects_controller.rb
class SubjectsController < ApplicationController
  def show
    @subject = Subject.find params[:id]
  end

  def index
    @subjects = Subject.all
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      session[:user_id] = @user.id
      redirect_to user_path(@user.id), :notice => "Account created.  Welcome #{@user.name}!"
    else
      render 'new'
    end
  end

  def show
    @user = User.find params[:id]
    # if current_user.id == @user.id 
      flash.now[:info] = "#{view_context.link_to('Account settings', edit_user_path(@user))}".html_safe
    # end
  end

  def edit
    @user = User.find params[:id]
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(params[:user])
      redirect_to user_path(@user.id), :notice => "Changes saved."
    else
      render 'edit'
    end
  end

  def add_course
    @user = User.find params[:id]
    @course = Course.find params[:course_id]
    @user.add_course @course

    redirect_to course_path(@course), :notice => "#{@course.ccode} has been added to your Course List"
  end

  def remove_course
    @user = User.find params[:id]
    @course = Course.find params[:course_id]
    @user.remove_course @course

    redirect_to course_path(@course), :notice => "#{@course.ccode} has been removed from your Course List"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def current_user
    begin
      @current_user ||= User.find(session[:user_id]) if session[:user_id]
    rescue ActiveRecord::RecordNotFound
      nil
    end
  end


end

app/helpers/comment_helper.rb
module CommentHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/courses/_course.html.erb
<h3><%= link_to( course.name, course_path(course) ) %></h3>

<ul>
  <strong>Course Code</strong>
  <li><%= course.ccode %></li>
  <strong>Credits</strong>
  <li><%= course.credits %></li>
  <strong>Course Coordinator</strong>
  <li><%= course.coordinator %></li>
  <strong>Pre-requesites</strong>
  <li><%= course.prereq %></li>
  <strong>Note</strong>
  <li><%= course.note %></li>
  <strong>Description</strong>
  <li><%= course.description %></li>
  <strong>Assessment</strong>
  <li><%= course.assessment %></li>
  <strong>Level</strong>
  <li><%= course.level %></li>
  <strong>Department</strong>
  <li><%= course.department %></li>
  <strong>Subject</strong>
  <li><%= link_to course.subject, subject_path( course.subject ) %></li>  
</ul>

app/views/courses/index.html.erb
<%= provide(:title, "All courses") %>

<h1>All Courses</h1>

<ul class="courses">
  <% @courses.each do |course| %>
  <li class="course">
    <%= render course %>
  </li>
  <% end -%>
</ul>

app/views/courses/show.html.erb
<% provide(:title, @course.name) %>

<% content_for :sidebar do %>
  <li class="nav-header">Course Actions</li>
  <li>Your 'Course List' is a list of all courses you have taken or are currently taking.</li>
  <br />
  <li><strong>Add courses to get the most out of ABDNCC</strong></li>
  <br />
  <% if current_user %>
    <% if current_user.has_course? @course %><!-- Show the 'Remove Course' button -->
      <li>
        <%= form_tag remove_course_user_path(current_user) do %>
          <%= hidden_field_tag 'course_id', @course.id %>
          <%= button_tag "Remove from my Course List", :class => 'btn btn-danger' %>
        <% end -%>
      </li>
    <% else %><!-- Show the 'Add Course' button -->
      <li>
        <%= form_tag add_course_user_path(current_user) do %>
          <%= hidden_field_tag 'course_id', @course.id %>
          <%= button_tag "Add to my Course List", :class => 'btn btn-success' %>
        <% end -%>
      </li>
    <% end -%>
  <% end -%><!-- /current-user -->
<% end -%><!-- /sidebar -->

<h2><%= @course.name %></h2>

<h3>Course Code</h3>
<p><%= @course.ccode %></p>

<h3>Credits</h3>
<p><%= @course.credits %></p>

<h3>Course Co-ordinator</h3>
<p><%= @course.coordinator %></p>

<h3>Prerequesites</h3>
<p><%= @course.prereq %></p>

<h3>Note(s)</h3>
<p><%= @course.note %></p>

<h3>Description</h3>
<p><%= @course.description %></p>

<h3>Assessment</h3>
<p><%= @course.assessment %></p>

<h3>Level</h3>
<p><%= @course.level %></p>

<h3>Subject</h3>
<p><%= link_to( @course.subject.name, subject_path(@course.subject) ) %></p>

<h3>Department</h3>
<p><%= @course.department %></p>

<h2>Comments</h2>

<!-- Add Comment box -->
<% if current_user %>
  <%= form_for Comment.new do |f| %>
    <% if @comment.errors.any? %>
      <div class="error_messages">
        <h2>Oops!</h2>
        <ul>
          <% for message in @user.errors.full_messages %>
            <li><%= message %></li>
          <% end -%>
        </ul>
      </div>
    <% end -%>
    <%= f.text_area :content, :placeholder => "Write something and then click 'Add Comment'!" %>
    <%= f.hidden_field :user_id, :value => current_user.id %>
    <%= f.hidden_field :course_id, :value => @course.id %>
    <%= f.button "Add Comment", :class => 'btn btn-primary' %>
  <% end -%>

<% else %>
  <p class='success'>Sign up for an account to contribute</p>
<% end -%>


<div class="comments">
  <% @course.comments.each do |comment| %>
  <div class="comment">
    <h4><%= comment.user.name %> <small><%= comment.user.status %></small></h4>
    <h6><%= comment.created_at.to_s %></h6>
    <p><%= comment.content %></p>
  </div>
  <% end -%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? "ABDNCC: #{yield(:title)}" : "ABDNCC" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <link href="images/favicon.ico" rel="shortcut icon">
    <link href="images/apple-touch-icon.png" rel="apple-touch-icon">
    <link href="images/apple-touch-icon-72x72.png" rel="apple-touch-icon" sizes="72x72">
    <link href="images/apple-touch-icon-114x114.png" rel="apple-touch-icon" sizes="114x114">
  </head>
  <body>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container-fluid">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <%= link_to "Aberdeen Course Catalogue", root_url, :class => 'brand' %></a>
          <div class="container-fluid nav-collapse">
            <ul class="nav">
              <li><%= link_to "Courses", courses_path  %></li>
              <li><%= link_to "Subjects", subjects_path  %></li>
            </ul>
            <ul class="nav pull-right">
              <% if current_user %>
                <li><%= link_to current_user.name, user_path(current_user) %></li>
                <li><%= link_to "Log out", session_path(current_user.id), :method => :delete  %></li>
              <% else %>
                <li><%= link_to "Sign up", new_user_path %></li>
                <li><%= link_to "Log in", new_session_path %></li>
              <% end -%>
            </ul>
              <%= form_tag '/search',  :class => "navbar-search pull-left"  do %>
                <%= text_field_tag :query, params[:query], :placeholder => 'Search Courses', :class => 'search-query' %>
                <%= submit_tag "search", :disabled => false, :class => 'hide' %>
              <% end %>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container-fluid">
      <div class="row-fluid">
        <div class="span3">
          <div class="well sidebar-nav">
            <ul class="nav nav-list">
              <%= yield :sidebar %>
              <!-- <li class="nav-header">Sidebar</li>
              <li><%= link_to "Link1", "/path1"  %></li>
              <li><%= link_to "Link2", "/path2"  %></li>
              <li><%= link_to "Link3", "/path3"  %></li> -->
            </ul>
          </div><!--/.well -->
        </div><!--/span-->
        <div class="span9">
          <%= flash_block %>
          <%= yield %>
        </div>
      </div><!--/row-->

      <footer>
        <p>&copy; Company 2012</p>
      </footer>

    </div> <!-- /container -->

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>

  </body>
</html>

app/views/subjects/index.html.erb
<% provide(:title, 'Catalogue of Courses (Undergraduate)') %>

<h2>Course Index By Subject</h2>
<ul class="subjects">
  <% @subjects.each do |subj| %>
  <li class="subject">
    <%= link_to( subj.name, subject_path(subj) )%> (<%= subj.code %>)
  </li>
  <% end -%>
</ul>

app/views/subjects/show.html.erb
<% provide(:title, @subject.name) %>

<!-- Contents -->
<!-- THIS SECTION IS UNTESTED - TODO: FIND A WAY TO TEST THIS -->
<% content_for :sidebar do %>
<div class="contents">
  <li class='nav-header'>Jump to Levels</li>
    <li>
      <%= link_to( "Level One", subject_path(@subject, :anchor => 'level1') ) %>
    </li>
    <li>
      <%= link_to( "Level Two", subject_path(@subject, :anchor => 'level2') ) %>
    </li>
    <li>
      <%= link_to( "Level Three", subject_path(@subject, :anchor => 'level3') ) %>
    </li>
    <li>
      <%= link_to( "Level Four", subject_path(@subject, :anchor => 'level4') ) %>
    </li>
</div>
<% end -%>



<!-- Page header -->
<h1><%= @subject.name %></h1>

<!-- Course list for this subject -->
<ul class="courses">

<!-- Level 1 -->
<a name='level1'><h2>Level One <small><a href="#top">(top)</a></small></h2></a>
<% @subject.courses_where(:level => 1).each do |course| %>
  <li class="course">
    <%= render course %>
  </li>
<% end -%>  

<!-- Level 2 -->
<a name='level2'><h2>Level Two <small><a href="#top">(top)</a></small></h2></a>
<% @subject.courses_where(:level => 2).each do |course| %>
  <li class="course">
    <%= render course %>
  </li>
<% end -%>  

<!-- Level 3 -->
<a name='level3'><h2>Level Three <small><a href="#top">(top)</a></small></h2></a>
<% @subject.courses_where(:level => 3).each do |course| %>
  <li class="course">
    <%= render course %>
  </li>
<% end -%>  

<!-- Level 4 -->
<a name='level4'><h2>Level Four <small><a href="#top">(top)</a></small></h2></a>
<% @subject.courses_where(:level => 4).each do |course| %>
  <li class="course">
    <%= render course %>
  </li>
<% end -%>  

</ul><!-- END COURSE LIST -->

app/views/users/edit.html.erb
<% provide(:title, "Editing #{@user.name}") %>

<%= form_for @user, :html => { :class => "form-horizontal edit-user" } do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Oops!</h2>
      <ul>
        <% for message in @user.errors.full_messages %>
          <li><%= message %></li>
        <% end -%>
      </ul>
    </div>
  <% end -%>

  <fieldset>
    <div class="control-group">
      <%= f.label :name, :class => "control-label" %>
      <div class="controls">
        <%= f.text_field :name %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :status, :class => "control-label" %>
      <div class="controls">
        <%= f.text_field :status, :placeholder => 'Second-Year Anthropology MA' %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :email, :class => "control-label" %>
      <div class="controls">
        <%= f.text_field :email %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :password, :class => "control-label" %>
      <div class="controls">
        <%= f.password_field :password %>
        <p class="help-block">Required</p>
      </div>
    </div>     

    <div class="form-actions">
      <%= f.button "Save", :class => "btn btn-primary" %>
    </div>
  </fieldset>

<% end %>

app/views/users/new.html.erb
<% provide(:title, "Signup form") %>

<h1>New Account</h1>

<%= form_for User.new do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Oops!</h2>
      <!-- <h3>Your password is too short, or there might be a typo in your email address</h3> -->
      <ul>
        <% for message in @user.errors.full_messages %>
          <li><%= message %></li>
        <% end -%>
      </ul>
    </div>
  <% end -%>
  <%= f.text_field :email, :placeholder => "Email" %>
  <%= f.password_field :password, :placeholder => "Password" %>
  <%= f.button "Sign up" %>
<% end -%>  

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<!-- flash block pending bootstrap integration -->

<h2><%= @user.name %> <small> <%= @user.status %></small></h2>

<h3>Course List</h3>
<% @user.courses.each do |course| %>
  <ul class="courses">
    <li class="course"><%= render course %></li>
  </ul>
<% end -%>